"use client"

import type React from "react"
import { createContext, useContext, useEffect, useState } from "react"

export type Language = "es" | "en" | "qu"

interface LanguageContextType {
  language: Language
  setLanguage: (lang: Language) => void
  t: (key: string) => string
}

const LanguageContext = createContext<LanguageContextType | undefined>(undefined)

// ─── Translation dictionaries ─────────────────────────────────────────────────

export const translations: Record<Language, Record<string, string>> = {
  es: {
    // ── Home page ──
    "home.ministry": "Ministerio de Educación",
    "home.platform": "Plataforma Educativa Virtual",
    "home.login": "Iniciar Sesión",
    "home.register": "Registrarse",
    "home.badge": "Nueva Generación de Educación Digital",
    "home.description":
      "EDU conecta estudiantes, profesores y administradores en un entorno digital innovador, diseñado específicamente para potenciar el aprendizaje en el sistema educativo ecuatoriano.",
    "home.demo": "Explorar Demo",
    "home.features.title": "Funcionalidades de Vanguardia",
    "home.features.subtitle": "Herramientas modernas que revolucionan la experiencia educativa",
    "home.feat1.title": "Gestión Inteligente",
    "home.feat1.desc": "Perfiles diferenciados con IA para estudiantes, profesores y administradores",
    "home.feat2.title": "Currículo Adaptativo",
    "home.feat2.desc": "Organización completa del currículo ecuatoriano con contenido interactivo",
    "home.feat3.title": "Evaluación Avanzada",
    "home.feat3.desc": "Sistema de calificación inteligente adaptado al sistema educativo nacional",
    "home.feat4.title": "Planificación Smart",
    "home.feat4.desc": "Calendario académico inteligente con recordatorios automáticos",
    "home.feat5.title": "Comunicación 360°",
    "home.feat5.desc": "Mensajería en tiempo real y colaboración entre toda la comunidad educativa",
    "home.feat6.title": "Analytics Educativo",
    "home.feat6.desc": "Estadísticas avanzadas y análisis predictivo del rendimiento académico",
    "home.stats.schools": "Colegios Conectados",
    "home.stats.students": "Estudiantes Activos",
    "home.stats.teachers": "Profesores Certificados",
    "home.stats.satisfaction": "Satisfacción",
    "home.cta.title": "¿Listo para Revolucionar tu Institución?",
    "home.cta.desc": "Únete a cientos de colegios que ya están transformando la educación con EDU Ecuador",
    "home.cta.start": "Comenzar Prueba Gratuita",
    "home.cta.demo": "Agendar Demostración",
    "home.footer.platform": "Plataforma",
    "home.footer.features": "Funcionalidades",
    "home.footer.pricing": "Precios",
    "home.footer.demo": "Demo",
    "home.footer.integrations": "Integraciones",
    "home.footer.support": "Soporte",
    "home.footer.help": "Centro de Ayuda",
    "home.footer.contact": "Contacto",
    "home.footer.training": "Capacitación",
    "home.footer.community": "Comunidad",
    "home.footer.legal": "Legal",
    "home.footer.privacy": "Privacidad",
    "home.footer.terms": "Términos",
    "home.footer.security": "Seguridad",
    "home.footer.copy": "© 2024 EDU Ecuador. Todos los derechos reservados. Hecho con ❤️ para la educación ecuatoriana.",
    "home.footer.desc":
      "Transformando la educación en Ecuador a través de la innovación tecnológica y la excelencia académica.",

    // ── Login page ──
    "login.welcome": "Bienvenido a EDU",
    "login.subtitle": "Accede a tu cuenta para continuar con tus actividades académicas",
    "login.userType": "Tipo de Usuario",
    "login.selectRole": "Selecciona tu rol",
    "login.student": "Estudiante",
    "login.student.desc": "Acceso a cursos y tareas",
    "login.teacher": "Profesor",
    "login.teacher.desc": "Gestión de clases",
    "login.admin": "Administrador",
    "login.admin.desc": "Control total",
    "login.representative": "Representante",
    "login.representative.desc": "Seguimiento de alumnos",
    "login.email": "Correo Electrónico",
    "login.email.placeholder": "tu.email@colegio.edu.ec",
    "login.password": "Contraseña",
    "login.loading": "Iniciando sesión...",
    "login.submit": "Iniciar Sesión",
    "login.forgot": "¿Olvidaste tu contraseña?",
    "login.or": "o",
    "login.noAccount": "¿No tienes cuenta?",
    "login.register": "Regístrate aquí",

    // ── Teacher overview ──
    "teacher.panel": "Panel del Profesor",
    "teacher.subtitle": "Prof. Roberto García - Matemáticas",
    "teacher.profile": "Mi Perfil",
    "teacher.reports": "Mis Reportes",
    "teacher.schedule": "Mi Horario",
    "teacher.logout": "Cerrar Sesión",
    "teacher.logout.confirm": "¿Estás seguro de que deseas cerrar sesión?",
    "teacher.tab.overview": "Resumen",
    "teacher.tab.classes": "Clases",
    "teacher.tab.assignments": "Tareas",
    "teacher.tab.grades": "Calificaciones",
    "teacher.tab.resources": "Recursos",
    "teacher.tab.schedule": "Horario",
    "teacher.tab.reports": "Reportes",
    "teacher.stat.students": "Total Estudiantes",
    "teacher.stat.students.sub": "En 3 cursos",
    "teacher.stat.pending": "Tareas Pendientes",
    "teacher.stat.pending.sub": "Por revisar",
    "teacher.stat.average": "Promedio General",
    "teacher.stat.average.sub": "Todos los cursos",
    "teacher.stat.next": "Próxima Clase",
    "teacher.stat.next.sub": "En 2 horas",
    "teacher.recent.assignments": "Tareas Recientes",
    "teacher.recent.assignments.desc": "Estado de entrega de tareas asignadas",
    "teacher.recent.grades": "Calificaciones Recientes",
    "teacher.recent.grades.desc": "Últimas calificaciones ingresadas",
    "teacher.due": "Vence:",

    // ── Student overview ──
    "student.greeting": "¡Hola,",
    "student.logout": "Cerrar Sesión",
    "student.logout.confirm": "¿Estás seguro de que deseas cerrar sesión?",
    "student.profile": "Mi Perfil",
    "student.settings": "Configuración",
    "student.grades": "Mis Calificaciones",
    "student.tab.overview": "Resumen",
    "student.tab.grades": "Calificaciones",
    "student.tab.assignments": "Tareas",
    "student.tab.schedule": "Horario",
    "student.tab.library": "Biblioteca",
    "student.tab.analytics": "Análisis",
    "student.tab.gamification": "Logros",
    "student.tab.chat": "Chat",
    "student.tab.representative": "Vista Representante",
    "student.stat.average": "Promedio General",
    "student.stat.average.sub": "Excelente rendimiento",
    "student.stat.attendance": "Asistencia",
    "student.stat.attendance.sub": "Muy buena asistencia",
    "student.stat.completed": "Tareas Completadas",
    "student.stat.completed.sub": "completado",
    "student.stat.ranking": "Ranking",
    "student.stat.ranking.sub": "de",
    "student.stat.ranking.sub2": "estudiantes",
    "student.recent.grades": "Calificaciones Recientes",
    "student.recent.grades.desc": "Tus últimas evaluaciones",
    "student.upcoming": "Próximas Entregas",
    "student.upcoming.desc": "Tareas y proyectos pendientes",
    "student.today": "Horario de Hoy",
    "student.today.desc": "Tus clases programadas para hoy",
    "student.priority.high": "Urgente",
    "student.priority.medium": "Medio",
    "student.priority.low": "Bajo",

    // ── Calendar / Schedule component ──
    "cal.title": "Calendario Académico",
    "cal.view.month": "Mes",
    "cal.view.week": "Semana",
    "cal.view.day": "Día",
    "cal.new.event": "Nuevo Evento",
    "cal.dialog.title": "Crear Nuevo Evento",
    "cal.field.title": "Título",
    "cal.field.title.placeholder": "Título del evento",
    "cal.field.desc": "Descripción",
    "cal.field.desc.placeholder": "Descripción del evento",
    "cal.field.date": "Fecha",
    "cal.field.time": "Hora",
    "cal.field.type": "Tipo",
    "cal.field.type.placeholder": "Seleccionar tipo",
    "cal.field.priority": "Prioridad",
    "cal.field.priority.placeholder": "Seleccionar prioridad",
    "cal.field.location": "Ubicación",
    "cal.field.location.placeholder": "Ubicación del evento",
    "cal.type.exam": "Examen",
    "cal.type.assignment": "Tarea",
    "cal.type.class": "Clase",
    "cal.type.event": "Evento",
    "cal.type.holiday": "Feriado",
    "cal.priority.high": "Alta",
    "cal.priority.medium": "Media",
    "cal.priority.low": "Baja",
    "cal.btn.cancel": "Cancelar",
    "cal.btn.create": "Crear Evento",
    "cal.sidebar.upcoming": "Próximos Eventos",
    "cal.sidebar.summary": "Resumen del Mes",
    "cal.summary.exams": "Exámenes",
    "cal.summary.assignments": "Tareas",
    "cal.summary.events": "Eventos",
    "cal.summary.classdays": "Días de clase",
    "cal.more": "más",
    "cal.allday": "Todo el día",
    "cal.months": "Enero,Febrero,Marzo,Abril,Mayo,Junio,Julio,Agosto,Septiembre,Octubre,Noviembre,Diciembre",
    "cal.days": "Dom,Lun,Mar,Mié,Jue,Vie,Sáb",

    // ── Student Grades tab ──
    "grades.title": "Mis Calificaciones",
    "grades.desc": "Historial completo de evaluaciones",
    "grades.col.subject": "Materia",
    "grades.col.partial1": "Parcial 1",
    "grades.col.partial2": "Parcial 2",
    "grades.col.assignments": "Tareas",
    "grades.col.average": "Promedio",
    "grades.subject.math": "Matemáticas",
    "grades.subject.science": "Ciencias",
    "grades.subject.language": "Lenguaje",
    "grades.subject.history": "Historia",
  },

  en: {
    // ── Home page ──
    "home.ministry": "Ministry of Education",
    "home.platform": "Virtual Educational Platform",
    "home.login": "Log In",
    "home.register": "Register",
    "home.badge": "Next Generation of Digital Education",
    "home.description":
      "EDU connects students, teachers, and administrators in an innovative digital environment, specifically designed to enhance learning in the Ecuadorian education system.",
    "home.demo": "Explore Demo",
    "home.features.title": "Cutting-Edge Features",
    "home.features.subtitle": "Modern tools that revolutionize the educational experience",
    "home.feat1.title": "Smart Management",
    "home.feat1.desc": "AI-powered differentiated profiles for students, teachers, and administrators",
    "home.feat2.title": "Adaptive Curriculum",
    "home.feat2.desc": "Complete organization of the Ecuadorian curriculum with interactive content",
    "home.feat3.title": "Advanced Assessment",
    "home.feat3.desc": "Intelligent grading system adapted to the national education system",
    "home.feat4.title": "Smart Planning",
    "home.feat4.desc": "Intelligent academic calendar with automatic reminders",
    "home.feat5.title": "360° Communication",
    "home.feat5.desc": "Real-time messaging and collaboration across the entire educational community",
    "home.feat6.title": "Educational Analytics",
    "home.feat6.desc": "Advanced statistics and predictive analysis of academic performance",
    "home.stats.schools": "Connected Schools",
    "home.stats.students": "Active Students",
    "home.stats.teachers": "Certified Teachers",
    "home.stats.satisfaction": "Satisfaction",
    "home.cta.title": "Ready to Revolutionize Your Institution?",
    "home.cta.desc": "Join hundreds of schools already transforming education with EDU Ecuador",
    "home.cta.start": "Start Free Trial",
    "home.cta.demo": "Schedule a Demo",
    "home.footer.platform": "Platform",
    "home.footer.features": "Features",
    "home.footer.pricing": "Pricing",
    "home.footer.demo": "Demo",
    "home.footer.integrations": "Integrations",
    "home.footer.support": "Support",
    "home.footer.help": "Help Center",
    "home.footer.contact": "Contact",
    "home.footer.training": "Training",
    "home.footer.community": "Community",
    "home.footer.legal": "Legal",
    "home.footer.privacy": "Privacy",
    "home.footer.terms": "Terms",
    "home.footer.security": "Security",
    "home.footer.copy": "© 2024 EDU Ecuador. All rights reserved. Made with ❤️ for Ecuadorian education.",
    "home.footer.desc":
      "Transforming education in Ecuador through technological innovation and academic excellence.",

    // ── Login page ──
    "login.welcome": "Welcome to EDU",
    "login.subtitle": "Log in to your account to continue with your academic activities",
    "login.userType": "User Type",
    "login.selectRole": "Select your role",
    "login.student": "Student",
    "login.student.desc": "Access to courses and assignments",
    "login.teacher": "Teacher",
    "login.teacher.desc": "Class management",
    "login.admin": "Administrator",
    "login.admin.desc": "Full control",
    "login.representative": "Representative",
    "login.representative.desc": "Student tracking",
    "login.email": "Email Address",
    "login.email.placeholder": "your.email@school.edu",
    "login.password": "Password",
    "login.loading": "Logging in...",
    "login.submit": "Log In",
    "login.forgot": "Forgot your password?",
    "login.or": "or",
    "login.noAccount": "Don't have an account?",
    "login.register": "Register here",

    // ── Teacher overview ──
    "teacher.panel": "Teacher Dashboard",
    "teacher.subtitle": "Prof. Roberto García - Mathematics",
    "teacher.profile": "My Profile",
    "teacher.reports": "My Reports",
    "teacher.schedule": "My Schedule",
    "teacher.logout": "Log Out",
    "teacher.logout.confirm": "Are you sure you want to log out?",
    "teacher.tab.overview": "Overview",
    "teacher.tab.classes": "Classes",
    "teacher.tab.assignments": "Assignments",
    "teacher.tab.grades": "Grades",
    "teacher.tab.resources": "Resources",
    "teacher.tab.schedule": "Schedule",
    "teacher.tab.reports": "Reports",
    "teacher.stat.students": "Total Students",
    "teacher.stat.students.sub": "In 3 courses",
    "teacher.stat.pending": "Pending Assignments",
    "teacher.stat.pending.sub": "To review",
    "teacher.stat.average": "Overall Average",
    "teacher.stat.average.sub": "All courses",
    "teacher.stat.next": "Next Class",
    "teacher.stat.next.sub": "In 2 hours",
    "teacher.recent.assignments": "Recent Assignments",
    "teacher.recent.assignments.desc": "Submission status of assigned tasks",
    "teacher.recent.grades": "Recent Grades",
    "teacher.recent.grades.desc": "Last grades entered",
    "teacher.due": "Due:",

    // ── Student overview ──
    "student.greeting": "Hello,",
    "student.logout": "Log Out",
    "student.logout.confirm": "Are you sure you want to log out?",
    "student.profile": "My Profile",
    "student.settings": "Settings",
    "student.grades": "My Grades",
    "student.tab.overview": "Overview",
    "student.tab.grades": "Grades",
    "student.tab.assignments": "Assignments",
    "student.tab.schedule": "Schedule",
    "student.tab.library": "Library",
    "student.tab.analytics": "Analytics",
    "student.tab.gamification": "Achievements",
    "student.tab.chat": "Chat",
    "student.tab.representative": "Representative View",
    "student.stat.average": "Overall Average",
    "student.stat.average.sub": "Excellent performance",
    "student.stat.attendance": "Attendance",
    "student.stat.attendance.sub": "Very good attendance",
    "student.stat.completed": "Completed Assignments",
    "student.stat.completed.sub": "completed",
    "student.stat.ranking": "Ranking",
    "student.stat.ranking.sub": "of",
    "student.stat.ranking.sub2": "students",
    "student.recent.grades": "Recent Grades",
    "student.recent.grades.desc": "Your latest evaluations",
    "student.upcoming": "Upcoming Deadlines",
    "student.upcoming.desc": "Pending tasks and projects",
    "student.today": "Today's Schedule",
    "student.today.desc": "Your classes scheduled for today",
    "student.priority.high": "Urgent",
    "student.priority.medium": "Medium",
    "student.priority.low": "Low",

    // ── Calendar / Schedule component ──
    "cal.title": "Academic Calendar",
    "cal.view.month": "Month",
    "cal.view.week": "Week",
    "cal.view.day": "Day",
    "cal.new.event": "New Event",
    "cal.dialog.title": "Create New Event",
    "cal.field.title": "Title",
    "cal.field.title.placeholder": "Event title",
    "cal.field.desc": "Description",
    "cal.field.desc.placeholder": "Event description",
    "cal.field.date": "Date",
    "cal.field.time": "Time",
    "cal.field.type": "Type",
    "cal.field.type.placeholder": "Select type",
    "cal.field.priority": "Priority",
    "cal.field.priority.placeholder": "Select priority",
    "cal.field.location": "Location",
    "cal.field.location.placeholder": "Event location",
    "cal.type.exam": "Exam",
    "cal.type.assignment": "Assignment",
    "cal.type.class": "Class",
    "cal.type.event": "Event",
    "cal.type.holiday": "Holiday",
    "cal.priority.high": "High",
    "cal.priority.medium": "Medium",
    "cal.priority.low": "Low",
    "cal.btn.cancel": "Cancel",
    "cal.btn.create": "Create Event",
    "cal.sidebar.upcoming": "Upcoming Events",
    "cal.sidebar.summary": "Month Summary",
    "cal.summary.exams": "Exams",
    "cal.summary.assignments": "Assignments",
    "cal.summary.events": "Events",
    "cal.summary.classdays": "Class days",
    "cal.more": "more",
    "cal.allday": "All day",
    "cal.months": "January,February,March,April,May,June,July,August,September,October,November,December",
    "cal.days": "Sun,Mon,Tue,Wed,Thu,Fri,Sat",

    // ── Student Grades tab ──
    "grades.title": "My Grades",
    "grades.desc": "Complete evaluation history",
    "grades.col.subject": "Subject",
    "grades.col.partial1": "Midterm 1",
    "grades.col.partial2": "Midterm 2",
    "grades.col.assignments": "Assignments",
    "grades.col.average": "Average",
    "grades.subject.math": "Mathematics",
    "grades.subject.science": "Science",
    "grades.subject.language": "Language",
    "grades.subject.history": "History",
  },

  qu: {
    // ── Kichwa / Quechua ecuatoriano ── (página de inicio)
    "home.ministry": "Yachay Ministiryu",
    "home.platform": "Kamachiy Yachay Ñan Virtual",
    "home.login": "Yaykuy",
    "home.register": "Qillqakuy",
    "home.badge": "Musu Wiñay Digital Yachay",
    "home.description":
      "EDU yachakukkuna, yachachikkuna shinallata kamachikkuna tupachiy, musu digital tiyaypi, Ecuador mama llaktapi yachaykunata kallpachakpi.",
    "home.demo": "Rikunapaq Yaykuy",
    "home.features.title": "Punta Ruraykunami",
    "home.features.subtitle": "Musu llankaykunami yachay kawsayta tikranku",
    "home.feat1.title": "Yuyay Kamachiy",
    "home.feat1.desc": "IA yanapaywan yachakukkunapaq, yachachikkunapaq shinallata kamachikkunapaq raquirishka rikachiykuna",
    "home.feat2.title": "Tikrakuy Yachay Ñan",
    "home.feat2.desc": "Ecuador yachay ñanpa punchunmantapim intirakunata rurashka musuq llankaykunawan",
    "home.feat3.title": "Sinchi Tupachiy",
    "home.feat3.desc": "Yuyay tupachiy sistema llakta yachay sistemaman tikrachishka",
    "home.feat4.title": "Yuyay Ruray Ñan",
    "home.feat4.desc": "Yuyay yachay killka kuyaywan killkarishka willaykuna churashpa",
    "home.feat5.title": "Rimay 360°",
    "home.feat5.desc": "Kunan pacha rimanakuy shinallata llakta yachay ayllupi llankay",
    "home.feat6.title": "Yachay Tupay",
    "home.feat6.desc": "Sinchi estadístikakuna shinallata yachay ñanta allichana tupachiy",
    "home.stats.schools": "Tupashka Yachay Wasikuna",
    "home.stats.students": "Kawsay Yachakukkuna",
    "home.stats.teachers": "Killkashka Yachachikkuna",
    "home.stats.satisfaction": "Kusikuy",
    "home.cta.title": "¿Kan Llankay Wasita Tikrayta Munankichu?",
    "home.cta.desc": "Patsak yachay wasikuna EDU Ecuador-wan yachаyta tikrachkankuna, paykunawan tinkuy",
    "home.cta.start": "Mana Pakay Qallariy",
    "home.cta.demo": "Rikunapaq Churay",
    "home.footer.platform": "Kamachiy Ñan",
    "home.footer.features": "Ruraykunа",
    "home.footer.pricing": "Chanikunа",
    "home.footer.demo": "Demo",
    "home.footer.integrations": "Tinkuykunа",
    "home.footer.support": "Yanapay",
    "home.footer.help": "Yanapay Wasi",
    "home.footer.contact": "Tupanakuy",
    "home.footer.training": "Yachachiy",
    "home.footer.community": "Ayllu",
    "home.footer.legal": "Kamachiy",
    "home.footer.privacy": "Pakachiy",
    "home.footer.terms": "Kамachikuna",
    "home.footer.security": "Wawachiy",
    "home.footer.copy": "© 2024 EDU Ecuador. Tukuy pachakuna wawachaшka. ❤️-wan Ecuador yachaykunapaq ruraшka.",
    "home.footer.desc":
      "Ecuador yachaykunata musu tecnología shinallata yachay allichaywan tikrachkanchik.",

    // ── Yaykuy panka (Login page) ──
    "login.welcome": "Alliklla Shamurkiy EDU-man",
    "login.subtitle": "Kan cuentaman yaykuy yachay llankaykunata katichun",
    "login.userType": "Ima Kashkamanta",
    "login.selectRole": "Kan rolnikita akllay",
    "login.student": "Yachakuk",
    "login.student.desc": "Yachaykunaman shinallata llankaykunaman yaykuy",
    "login.teacher": "Yachachik",
    "login.teacher.desc": "Clasekuna kamachiy",
    "login.admin": "Kamachik",
    "login.admin.desc": "Tukuy kamachiy",
    "login.representative": "Riksichik",
    "login.representative.desc": "Yachakukkunata katiy",
    "login.email": "Elektronika Willayñan",
    "login.email.placeholder": "kaniki.email@yachay.edu.ec",
    "login.password": "Pakashka Rimay",
    "login.loading": "Yaykuchkani...",
    "login.submit": "Yaykuy",
    "login.forgot": "Pakashka rimaynikita qunkarankichu?",
    "login.or": "mana chayqa",
    "login.noAccount": "Manachu cuentaniki tiyan?",
    "login.register": "Kaypi qillqakuy",

    // ── Yachachik Resumen (Teacher overview) ──
    "teacher.panel": "Yachachik Panka",
    "teacher.subtitle": "Prof. Roberto García - Matemáticas",
    "teacher.profile": "Ñuka Rikuchiy",
    "teacher.reports": "Ñuka Willakuykuna",
    "teacher.schedule": "Ñuka Pacha Ñan",
    "teacher.logout": "Llukshiy",
    "teacher.logout.confirm": "Chekatachu llukshiyta munankichu?",
    "teacher.tab.overview": "Kumuykuy",
    "teacher.tab.classes": "Clasekuna",
    "teacher.tab.assignments": "Llankaykunа",
    "teacher.tab.grades": "Tupachikuna",
    "teacher.tab.resources": "Yanapakykuna",
    "teacher.tab.schedule": "Pacha Ñan",
    "teacher.tab.reports": "Willakuykuna",
    "teacher.stat.students": "Tukuy Yachakukkuna",
    "teacher.stat.students.sub": "3 cursopi",
    "teacher.stat.pending": "Suyukuy Llankaykunа",
    "teacher.stat.pending.sub": "Chapakuyta tiyan",
    "teacher.stat.average": "Tukuy Chawpi",
    "teacher.stat.average.sub": "Tukuy cursokunapi",
    "teacher.stat.next": "Katik Clase",
    "teacher.stat.next.sub": "2 hora qipami",
    "teacher.recent.assignments": "Musu Llankaykunа",
    "teacher.recent.assignments.desc": "Llankay apachiy killkay",
    "teacher.recent.grades": "Musu Tupachikuna",
    "teacher.recent.grades.desc": "Qipa churashka tupachikuna",
    "teacher.due": "Tukukuna:",

    // ── Yachakuk Resumen (Student overview) ──
    "student.greeting": "Alliklla,",
    "student.logout": "Llukshiy",
    "student.logout.confirm": "Chekatachu llukshiyta munankichu?",
    "student.profile": "Ñuka Rikuchiy",
    "student.settings": "Churaykunа",
    "student.grades": "Ñuka Tupachikuna",
    "student.tab.overview": "Kumuykuy",
    "student.tab.grades": "Tupachikuna",
    "student.tab.assignments": "Llankaykunа",
    "student.tab.schedule": "Pacha Ñan",
    "student.tab.library": "Qillqa Wasi",
    "student.tab.analytics": "Tupay",
    "student.tab.gamification": "Chaninkuna",
    "student.tab.chat": "Rimanakuy",
    "student.tab.representative": "Riksichik Riku",
    "student.stat.average": "Tukuy Chawpi",
    "student.stat.average.sub": "Allin yachay",
    "student.stat.attendance": "Shamuy",
    "student.stat.attendance.sub": "Allin shamuy",
    "student.stat.completed": "Tukuchishka Llankaykunа",
    "student.stat.completed.sub": "tukunchishka",
    "student.stat.ranking": "Ñawpa Kay",
    "student.stat.ranking.sub": "manta",
    "student.stat.ranking.sub2": "yachakukkuna",
    "student.recent.grades": "Musu Tupachikuna",
    "student.recent.grades.desc": "Qipa tupachikuna",
    "student.upcoming": "Katik Apachikuna",
    "student.upcoming.desc": "Suyukuy llankay shinallata proyectokuna",
    "student.today": "Kunan Pacha Ñan",
    "student.today.desc": "Kunan punchapak clasekuna",
    "student.priority.high": "Usqaymi",
    "student.priority.medium": "Chawpi",
    "student.priority.low": "Ura",

    // ── Pacha Ñan / Horario (Calendar component) ──
    "cal.title": "Yachay Pacha Killka",
    "cal.view.month": "Killa",
    "cal.view.week": "Semana",
    "cal.view.day": "Punchay",
    "cal.new.event": "Musu Tukuy",
    "cal.dialog.title": "Musu Tukuy Ruray",
    "cal.field.title": "Suti",
    "cal.field.title.placeholder": "Tukuypa suti",
    "cal.field.desc": "Willakuy",
    "cal.field.desc.placeholder": "Tukuymanta willakuy",
    "cal.field.date": "Punchay",
    "cal.field.time": "Pacha",
    "cal.field.type": "Ima Kasta",
    "cal.field.type.placeholder": "Ima kastata akllay",
    "cal.field.priority": "Ñawpa Kay",
    "cal.field.priority.placeholder": "Ñawpa kayta akllay",
    "cal.field.location": "Tiyay",
    "cal.field.location.placeholder": "Tukuy tiyay",
    "cal.type.exam": "Tupachiy",
    "cal.type.assignment": "Llankay",
    "cal.type.class": "Yachay",
    "cal.type.event": "Tukuy",
    "cal.type.holiday": "Samarikuy",
    "cal.priority.high": "Sinchi",
    "cal.priority.medium": "Chawpi",
    "cal.priority.low": "Ura",
    "cal.btn.cancel": "Saquiy",
    "cal.btn.create": "Tukuyta Ruray",
    "cal.sidebar.upcoming": "Katik Tukuykuna",
    "cal.sidebar.summary": "Killamanta Kumuykuy",
    "cal.summary.exams": "Tupachikuna",
    "cal.summary.assignments": "Llankaykunа",
    "cal.summary.events": "Tukuykuna",
    "cal.summary.classdays": "Yachay punchaykuna",
    "cal.more": "aswan",
    "cal.allday": "Tukuy punchay",
    "cal.months": "Qulla Raymi,Hatun Pucuy,Pauqar Waray,Ayriwa,Aymuray,Inti Raymi,Anta Situa,Qhapaq Situa,Uma Raymi,Kantaray,Ayamarq'ay,Kapaq Raymi",
    "cal.days": "Intip,Killap,Atiq,Qullqip,Illapap,Ch'askap,Kuyuchip",

    // ── Yachakuk Tupachikuna (Student Grades tab) ──
    "grades.title": "Ñuka Tupachikuna",
    "grades.desc": "Tukuy tupachiykunapa killkay",
    "grades.col.subject": "Yachay",
    "grades.col.partial1": "Ñawpak Tupachiy",
    "grades.col.partial2": "Iskay Tupachiy",
    "grades.col.assignments": "Llankaykunа",
    "grades.col.average": "Chawpi",
    "grades.subject.math": "Yupay Yachay",
    "grades.subject.science": "Kawsay Yachay",
    "grades.subject.language": "Rimay Yachay",
    "grades.subject.history": "Ñawpa Kawsay",
  },
}

// ─── Provider ─────────────────────────────────────────────────────────────────

export function LanguageProvider({ children }: { children: React.ReactNode }) {
  const [language, setLanguageState] = useState<Language>("es")

  useEffect(() => {
    const saved = localStorage.getItem("edu-language") as Language
    if (saved === "es" || saved === "en" || saved === "qu") setLanguageState(saved)
  }, [])

  const setLanguage = (lang: Language) => {
    setLanguageState(lang)
    localStorage.setItem("edu-language", lang)
  }

  const t = (key: string): string =>
    translations[language][key] ?? translations["es"][key] ?? key

  return (
    <LanguageContext.Provider value={{ language, setLanguage, t }}>
      {children}
    </LanguageContext.Provider>
  )
}

// ─── Hook ─────────────────────────────────────────────────────────────────────

export function useLanguage() {
  const context = useContext(LanguageContext)
  if (context === undefined) {
    throw new Error("useLanguage must be used within a LanguageProvider")
  }
  return context
}
